[project]
name = "pandas-overview-nb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "notebook>=7.3.2",
    "pandas>=2.2.3",
]
